### ISSUE TITLE
numpy.linalg.LinAlgError: Singular matrix

### ISSUE THREAD

**Issue by ghost** [LearnerLee/KITTI-odometry-evaluation-tool#2]
I generate a pose.txt from my SLAM algorithm.

while this tools throw an error, while I test on [another](https://github.com/MichaelGrupp/evo) evaluation tools it works fine.

could you kindly tell me the reason?

```
ZZZZ@DeskPC:~/Desktop/visual_odometry/KITTI_odometry_evaluation_tool$ python3 evaluation.py --result_dir=./data/ --eva_seqs=09_pred
Traceback (most recent call last):
  File "evaluation.py", line 663, in <module>
    pose_eval.eval(toCameraCoord=args.toCameraCoord)   # set the value according to the predicted results
  File "evaluation.py", line 592, in eval
    seq_err = self.calcSequenceErrors(poses_gt, poses_result)
  File "evaluation.py", line 165, in calcSequenceErrors
    pose_error = np.dot(np.linalg.inv(pose_delta_result), pose_delta_gt)
  File "/usr/local/lib/python3.5/dist-packages/numpy/linalg/linalg.py", line 551, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/usr/local/lib/python3.5/dist-packages/numpy/linalg/linalg.py", line 97, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix

```

**Comment by Charlesl0129** [comment]
Hi carpdm did you end up solving this issue? I also got this error.
